version: '3'
services:

  nginx:
    container_name: nginx
    image: nginx:alpine

    ports:
      - "8080:8080"

    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/main:/usr/share/nginx/html:ro"
